global:
  resolve_timeout: 5m
  # Slack webhook URL은 환경변수로 설정됨

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'slack-notifications'
  
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: false
    - match:
        severity: warning
      receiver: 'slack-warnings'
      continue: false

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'SLACK_WEBHOOK_URL_PLACEHOLDER'
        send_resolved: true
        channel: '#monitoring'
        title: 'Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        
  - name: 'slack-critical'
    slack_configs:
      - api_url: 'SLACK_WEBHOOK_URL_PLACEHOLDER'
        send_resolved: true
        channel: '#monitoring'
        username: 'Critical Alert'
        icon_emoji: ':rotating_light:'
        color: 'danger'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'slack-warnings'
    slack_configs:
      - api_url: 'SLACK_WEBHOOK_URL_PLACEHOLDER'
        send_resolved: true
        channel: '#monitoring'
        username: 'Warning Alert'
        icon_emoji: ':warning:'
        color: 'warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
